name: 'PantryPins'
version: '${version}'
main: me.pantrypins.plugin.PantryPins
api-version: '26.1'
depend: [NBTAPI]
softdepend:
  - ProtocolLib
  - PlaceholderAPI
  - packetevents
  - HeadDatabase
  - VaultAPI
  - Nexo
  - ItemsAdder
  - PlayerPoints
  - SimpleItemGenerator
  - ExecutableItems
  - SCore
authors: [PantryPins]
folia-supported: true
description: PantryPins - Tags for your server. (Fork of SupremeTags by Scape.)
commands:
  tags:
    description: Main command for PantryPins.
    usage: /<command>
    aliases:
      - tag
  mytags:
    description: Opens the personal tags menu.
    usage: /mytags
    permission: supremetags.mytags
